### ISSUE TITLE
[Feature Request] Allow Ravager griefing

### ISSUE THREAD

**Issue by RubyRezal** [A5b84/convenient-mobgriefing#14]
Ravagers have an odd behavior change when mobGriefing is set false.

Assuming mobGriefing true is intended default behavior, ravagers normally jump or float up at the edge of flowing water.  Setting mobGriefing false causes them to not jump or float up at the edge of a water stream.  I tested this without mods installed and verified this is a quirk in Vanilla Minecraft.  To verify independently, build the raid farm from the following video and test with mobGriefing in both true and false settings. https://www.youtube.com/watch?v=JHD6EINGWdE

This change in behavior causes some Raid Farm designs (like the one in the example video) to clog up with Ravagers that do not jump up into a lava blade to be destroyed as intended.  A separate gamerule to allow Ravager griefing similar to the rules for the Ender Dragon and Wither would help solve this problem.

Also, Ravagers only spawn with Raid waves which must be initiated by player action.  Since players can easily avoid starting raids, the summoning of ravagers and the risk of their destructive actions would logically fall under the category of consequences of player actions.

**Comment by A5b84** [comment]
Ravager griefing is now controlled by `lenientGriefing` in the latest version
