### ISSUE TITLE
Crash with No Trample

### ISSUE THREAD

**Issue by SpeedRider** [A5b84/convenient-mobgriefing#2]
https://paste.ee/p/b1FxH
IDK if it's your mods fault or not

**Comment by A5b84** [comment]
It's a compatibility issue (No Trample and my mod both modify the same thing), I'll probably just lower the priority of my stuff so I don't overwrite important stuff from other mods and that should be good

**Comment by A5b84** [comment]
Fixed in version 1.1.3
