### ISSUE TITLE
Crashes with Astromine and some other mods in 1.16.4

### ISSUE THREAD

**Issue by Neubulae** [A5b84/convenient-mobgriefing#3]
`[17:53:39] [main/FATAL]: Mixin prepare failed preparing IdentifierMixin in astromine.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: astromine.mixins.json:IdentifierMixin target net.minecraft.class_2960 was loaded too early.`

`[17:49:41] [main/FATAL]: Mixin prepare failed preparing MixinSharedConstants in sectionsign.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: sectionsign.mixins.json:MixinSharedConstants target net.minecraft.class_155 was loaded too early.`

Removing ConveGrief fixed the issue

**Comment by TwilightFlower** [comment]
This is due to line 19 of MixinConfigPlugin. Referencing Minecraft classes from a mixin config plugin causes a LOT of issues.

**Comment by A5b84** [comment]
Couldn't reproduce for some reason but should be fixed anyway
