### ISSUE TITLE
[1.16.5] 2.0.1/2.0.2 crashes the game on startup

### ISSUE THREAD

**Issue by zhguyu** [A5b84/convenient-mobgriefing#8]
As the title suggests, version 2.0.1 and 2.0.2 of this mod crashes the game on startup without any fabric errors and the launcher reports an error code 0. Version 2.0.0 works fine.

Fabric version: 0.11.6
Fabric API version: 0.40.0

Please see the attached log for a list of other mods installed.

[21:37:03] [main/INFO]: Loading for game Minecraft 1.16.5
[21:37:04] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+f74f7c7d7d, also found 1.0.4+9354966b7d
[21:37:04] [main/INFO]: [FabricLoader] Loading 64 mods:
	- architectury@1.20.29
	- bbor@2.4-1.16.3
	- carpet@1.4.44
	- cloth-basic-math@0.5.1
	- cloth-config2@4.11.26
	- compostable-rottenflesh@1.0.0
	- convenient-mobgriefing@2.0.2
	- fabric@0.40.0+1.16
	- fabric-api-base@0.3.0+f74f7c7d7d
	- fabric-api-lookup-api-v1@1.3.0+f74f7c7d7d
	- fabric-biome-api-v1@3.1.11+f74f7c7d7d
	- fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
	- fabric-command-api-v1@1.1.2+f74f7c7d7d
	- fabric-commands-v0@0.2.2+ca58154a7d
	- fabric-containers-v0@0.1.11+9354966b7d
	- fabric-content-registries-v0@0.2.4+f74f7c7d7d
	- fabric-crash-report-info-v1@0.1.3+ca58154a7d
	- fabric-dimensions-v1@2.0.6+f74f7c7d7d
	- fabric-entity-events-v1@1.2.3+77df1b337d
	- fabric-events-interaction-v0@0.4.4+35ff49a47d
	- fabric-events-lifecycle-v0@0.2.1+ca58154a7d
	- fabric-game-rule-api-v1@1.0.6+f74f7c7d7d
	- fabric-item-api-v1@1.2.1+ca58154a7d
	- fabric-item-groups-v0@0.2.7+2868a2287d
	- fabric-key-binding-api-v1@1.0.4+f74f7c7d7d
	- fabric-keybindings-v0@0.2.1+ca58154a7d
	- fabric-lifecycle-events-v1@1.2.1+ca58154a7d
	- fabric-loot-tables-v1@1.0.2+ca58154a7d
	- fabric-mining-levels-v0@0.1.3+ca58154a7d
	- fabric-models-v0@0.3.0+f74f7c7d7d
	- fabric-networking-api-v1@1.0.4+f74f7c7d7d
	- fabric-networking-blockentity-v0@0.2.8+ca58154a7d
	- fabric-networking-v0@0.3.2+ca58154a7d
	- fabric-object-builder-api-v1@1.9.5+f74f7c7d7d
	- fabric-object-builders-v0@0.7.2+ca58154a7d
	- fabric-particles-v1@0.2.4+ca58154a7d
	- fabric-registry-sync-v0@0.7.4+ca58154a7d
	- fabric-renderer-api-v1@0.4.4+f74f7c7d7d
	- fabric-renderer-indigo@0.4.4+ca58154a7d
	- fabric-renderer-registries-v1@2.3.0+f74f7c7d7d
	- fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
	- fabric-rendering-fluids-v1@0.1.13+ca58154a7d
	- fabric-rendering-v0@1.1.2+ca58154a7d
	- fabric-rendering-v1@1.6.0+2868a2287d
	- fabric-resource-loader-v0@0.4.7+f74f7c7d7d
	- fabric-screen-api-v1@1.0.0+c045166c7d
	- fabric-screen-handler-api-v1@1.1.5+f74f7c7d7d
	- fabric-structure-api-v1@1.1.11+ca0ef93d7d
	- fabric-tag-extensions-v0@1.1.1+ca58154a7d
	- fabric-textures-v0@1.0.6+ca58154a7d
	- fabric-tool-attribute-api-v1@1.2.7+f74f7c7d7d
	- fabric-transfer-api-v1@1.3.0+35ff49a47d
	- fabricloader@0.11.6
	- iris@1.1.2+build.4
	- java@11
	- litematica@0.0.0-dev.20210716.154721
	- lithium@0.6.6
	- malilib@0.10.0-dev.21+arne.8
	- minecraft@1.16.5
	- minihud@0.19.0-dev.20210215.151117
	- modmenu@1.16.11
	- sodium@0.2.0+IRIS4-build.4
	- starlight@fabric-1.0.0-RC2-82ae5ca
	- tweakeroo@0.10.0-dev.20210713.011628
[21:37:04] [main/WARN]: Mod `starlight` (fabric-1.0.0-RC2-82ae5ca) does not respect SemVer - comparison support is limited.
[21:37:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/zhguy/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

**Comment by zhguyu** [comment]
Just to clarify: game crushes with only convenient mobgriefing (2.0.1/2.0.2) and fabric api installed. So not a mod conflict issue.

**Comment by A5b84** [comment]
Versions 2.0.1 and 2.0.2 are only compatible with 1.17 and later due to the Java version change, I'll mark older versions as incompatible on CurseForge now
